### ISSUE TITLE
Prerendering fails when we have PWA enabled in blazor wasm app

### ISSUE THREAD

**Issue by fingers10** [Swimburger/BlazorWasmPrerender#1]
Prerendering with react snap works for .net 6 blazor wasm without pwa. But fails for .net 6 blazor wasm with pwa.

With PWA, I'm getting this error in prerender step:

🔥 pageerror at /: SyntaxError: Unexpected token '<'

🔥 pageerror at /: SyntaxError: Unexpected token '<'

🔥 pageerror at /: SyntaxError: Unexpected token '<'

🔥 pageerror at /: DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').

Please can you assist on this.

**Comment by Swimburger** [comment]
I haven't run into this issue yet with PWA, but I did have to update some of the scripts to match the .NET 6 output.
Here's a script updated for .NET 6, and combining what I wrote about in:
- [Pre-render Blazor WebAssembly at build time to optimize for search engines](https://swimburger.net/blog/dotnet/pre-render-blazor-webassembly-at-build-time-to-optimize-for-search-engines)
- [Fix Blazor WebAssembly PWA integrity checks](https://swimburger.net/blog/dotnet/fix-blazor-webassembly-pwa-integrity-checks)

```powershell
If(Test-Path .\Prerender\output)
{
    Remove-Item -Path .\Prerender\output -Recurse
}
 
dotnet publish .\Client\BlazorWasmPrerender.csproj -c Release -o Prerender/output --nologo
Push-Location .\Prerender
npx react-snap
Get-ChildItem ".\output\wwwroot\*.html" -Recurse | ForEach-Object { 
    $HtmlFileContent = (Get-Content -Path $_.FullName -Raw);
    $HtmlFileContent = $HtmlFileContent.Replace('<script>var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;</script><script src="_framework/dotnet.6.0.0.kq57fmx8bj.js" defer="" integrity="sha256-LOq52qjRa3+zt3w4UL10rS3UdwHxVQxW0JAsMPO9QAM=" crossorigin="anonymous"></script>','')
    Set-Content -Path $_.FullName -Value $HtmlFileContent
}

Push-Location .\output\wwwroot

# make sure you're in the wwwroot folder of the published application
$JsFileContent = Get-Content -Path service-worker-assets.js -Raw
# remove JavaScript from contents so it can be interpreted as JSON
$Json = $JsFileContent.Replace("self.assetsManifest = ", "").Replace(";", "") | ConvertFrom-Json
# grab the assets JSON array
$Assets = $Json.assets
foreach ($Asset in $Assets) {
  $OldHash = $Asset.hash
  $Path = $Asset.url
  
  $Signature = Get-FileHash -Path $Path -Algorithm SHA256
  $SignatureBytes = [byte[]] -split ($Signature.Hash -replace '..', '0x$& ')
  $SignatureBase64 = [System.Convert]::ToBase64String($SignatureBytes)
  $NewHash = "sha256-$SignatureBase64"
  
  If ($OldHash -ne $NewHash) {
    Write-Host "Updating hash for $Path from $OldHash to $NewHash"
    # slashes are escaped in the js-file, but PowerShell unescapes them automatically,
    # we need to re-escape them
    $OldHash = $OldHash.Replace("/", "\/")
    $NewHash = $NewHash.Replace("/", "\/")
    $JsFileContent = $JsFileContent.Replace("""$OldHash""", """$NewHash""")
  }
}

Set-Content -Path service-worker-assets.js -Value $JsFileContent -NoNewline

Pop-Location
```

After doing this, I am able to use `dotnet serve` and install as PWA.
```powershell
dotnet serve -o --directory "PreRender/output/wwwroot"
```

Here's the Bash version:

```bash
#!/bin/bash
rm -rf Prerender/output
dotnet publish Client/BlazorWasmPrerender.csproj -c Release -o Prerender/output --nologo

pushd Prerender

npx react-snap
find ./output -name "*.html" | while read htmlFile; do
    sed -i 's/<script>var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;<\/script><script src="_framework\/dotnet.6.0.0.kq57fmx8bj.js" defer="" integrity="sha256-LOq52qjRa3+zt3w4UL10rS3UdwHxVQxW0JAsMPO9QAM=" crossorigin="anonymous"><\/script>//g' $htmlFile
done

pushd Prerender

# make sure you're in the wwwroot folder of the published application
jsFile=$(<service-worker-assets.js)
# remove JavaScript from contents so it can be interpreted as JSON
json=$(echo "$jsFile" | sed "s/self.assetsManifest = //g" | sed "s/;//g")
# grab the assets JSON array
assets=$(echo "$json" | jq '.assets[]' -c)
for asset in $assets
do
  oldHash=$(echo "$asset" | jq '.hash')
  #remove leading and trailing quotes
  oldHash="${oldHash:1:-1}"
  path=$(echo "$asset" | jq '.url')
  #remove leading and trailing quotes
  path="${path:1:-1}"
  newHash="sha256-$(openssl dgst -sha256 -binary $path | openssl base64 -A)"
  
  if [ $oldHash != $newHash ]; then
    # escape slashes for json
    oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
    newHash=$(echo "$newHash" | sed 's;/;\\/;g')
    echo "Updating hash for $path from $oldHash to $newHash"
    # escape slashes second time for sed
    oldHash=$(echo "$oldHash" | sed 's;/;\\/;g')
    jsFile=$(echo -n "$jsFile" | sed "s;$oldHash;$newHash;g")
  fi
done

echo -n "$jsFile" > service-worker-assets.js

popd
popd
```

Both seem to work locally, and they "should" work the same when publishing to GitHub Pages.
Let me know if this helps, if it doesn't work on GitHub Pages, I'll have to do more digging.

**Comment by Swimburger** [comment]
I don't think it's related to PWA after all. After cloning your repo, I noticed you're using a dependency which kicks in during the build step to update the base-tag for you.
This step being redundant with the other script that does the same. There's no issue with both of them being there tho.
The problem seems to occur when you update the base-tags before running react-snap.
What I would suggest is publish without the `PublishSPAforGitHubPages.Build` dependency, then use react-snap, then use the script to update all HTML files with the correct base-tag.
You may also have to update the `start_url` in _manifest.json_.

Let me know if that helps.

**Comment by fingers10** [comment]
@Swimburger  many thanks for the inputs. I completely forgot the BuildSPA nuget. Removing that from the project dependency solves the issue. 

`start_url` in `manifest.json` should match `base` tag url of the fully qualified url of the site?

**Comment by Swimburger** [comment]
> @Swimburger many thanks for the inputs. I completely forgot the BuildSPA nuget. Removing that from the project dependency solves the issue.
> 
> `start_url` in `manifest.json` should match `base` tag url of the fully qualified url of the site?

I'm not sure what's the correct value for it. I don't remember ever running PWAs in a subdirectory.
